name: adventure_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cape_town.jpg
    - assets/joburg.jpg
    - assets/kruger.jpg
    - assets/durban.jpeg
    - assets/garden_route.jpeg
    - assets/hiking.webp
    - assets/safari.jpg
    - assets/scuba_diving.jpg
    - assets/surfing.jpg
    - assets/wine_tasting.jpg
    - assets/profile_image.webp